// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UglyMugCafe.Models;

namespace UglyMugCafe.Migrations
{
    [DbContext(typeof(OrderContext))]
    [Migration("20200519133644_UpdateOrder")]
    partial class UpdateOrder
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("UglyMugCafe.Models.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Bagel");

                    b.Property<DateTime>("CreateDate");

                    b.Property<string>("CustomerName")
                        .IsRequired();

                    b.Property<int>("DirtyHorchata");

                    b.Property<int>("Espresso");

                    b.Property<int>("IcedLatte");

                    b.Property<int>("StatusId");

                    b.Property<int>("TruffleFries");

                    b.Property<DateTime>("UpdateDate");

                    b.Property<int>("WMC");

                    b.HasKey("OrderId");

                    b.ToTable("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
